// Regenerates icons/Sticks/sticks-manifest.js from whatever PNGs are in that folder.
// The landing page (index.html) loads that manifest for the tool-preview resting figures.
//
//   Workflow:  drop PNGs into icons/Sticks/  →  node tools/gen-sticks.mjs
//
// Color rule: a figure keeps its own color when the filename ends in a 6-hex-digit
// suffix that contains a letter (e.g. ..._00bbd3.png, ...-FED12E.png). A trailing
// all-numeric segment is a Noun Project ID, not a color, so those are treated as
// pale/grey and get recolored per theme via CSS (see --fig-filter in index.html).

import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, '..', 'icons', 'Sticks');

const items = readdirSync(dir)
  .filter((f) => /\.png$/i.test(f))
  .sort((a, b) => a.localeCompare(b))
  .map((f) => {
    const m = f.match(/[-_]([0-9a-fA-F]{6})\.png$/);
    let c = m && /[a-fA-F]/.test(m[1]) ? '#' + m[1] : null;
    // Pure white is a neutral, not a brand color — recolor it per theme (like the
    // grey figures) so it stays visible on the light background too.
    if (c && c.toLowerCase() === '#ffffff') c = null;
    return { f, c };
  });

const out =
  '// AUTO-GENERATED by tools/gen-sticks.mjs — do not edit by hand.\n' +
  '// Drop PNGs into icons/Sticks/ then run: node tools/gen-sticks.mjs\n' +
  'window.EV_STICKS = ' + JSON.stringify(items, null, 2) + ';\n';

writeFileSync(join(dir, 'sticks-manifest.js'), out);

const colored = items.filter((i) => i.c).length;
console.log(`Wrote ${items.length} poses (${colored} colored, ${items.length - colored} recolored) to icons/Sticks/sticks-manifest.js`);
